# [ Reference ] GitHub Action Official Guide
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: sample-action

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  my_firsrt_job:
    runs-on:
      macos-latest
      # [ Reference ] GitHub-hosted runners
      # https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
      # https://docs.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - uses: Run a one-line script
        run: echo Hello world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
